apiVersion: v1
kind: Secret
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
  name: {{ include "spotfire-server.spotfiredatabase.secret.name" . | quote }}
data:
  # Reuse existing passwords when upgrading 
  {{- $secretCheck :=  (lookup "v1" "Secret" .Release.Namespace ( include "spotfire-server.spotfiredatabase.secret.name" . )) }}
  {{- if .Values.database.bootstrap.username }}
  SPOTFIREDB_USERNAME: {{ .Values.database.bootstrap.username | b64enc | quote }}
  {{- else if $secretCheck }}
  SPOTFIREDB_USERNAME: {{ index $secretCheck.data "SPOTFIREDB_USERNAME" }}
  {{- else }}
  SPOTFIREDB_USERNAME: {{ "spotfire" | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.bootstrap.password }}
  SPOTFIREDB_PASSWORD: {{ .Values.database.bootstrap.password | b64enc | quote }}
  {{- else if $secretCheck }}
  SPOTFIREDB_PASSWORD: {{ index $secretCheck.data "SPOTFIREDB_PASSWORD" }}
  {{- else }}
  SPOTFIREDB_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}