{{- if .Values.volumes.libraryImportExport.persistentVolumeClaim.create }}
{{- $pvcCheck :=  (lookup "v1" "PersistentVolumeClaim" .Release.Namespace ( include "spotfire-server.volumes.library-import-export.pvc.name" . )) }}
{{- if not $pvcCheck }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spotfire-server.volumes.library-import-export.pvc.name" . }}
  labels:
  {{- include "spotfire-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.volumes.libraryImportExport.persistentVolumeClaim.storageClassName | quote }}
  {{- with .Values.volumes.libraryImportExport.persistentVolumeClaim.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumeName: {{ .Values.volumes.libraryImportExport.persistentVolumeClaim.volumeName | quote }}
{{- end }}
{{- end }}