apiVersion: v1
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    {{- include "spotfire-server.labels" . | nindent 4 }}
  name: {{ include "spotfire-server.spotfireadmin.secret.name" . | quote }}
data:
  # Reuse existing passwords when upgrading
  {{- $secretCheck :=  (lookup "v1" "Secret" .Release.Namespace ( include "spotfire-server.spotfireadmin.secret.name" . )) }}
  {{- if $secretCheck }}
  SPOTFIREADMIN_PASSWORD: {{ index $secretCheck.data "SPOTFIREADMIN_PASSWORD" }}
  SPOTFIREADMIN_USERNAME: {{ index $secretCheck.data "SPOTFIREADMIN_USERNAME" }}
  {{- else }}
  SPOTFIREADMIN_USERNAME: {{ .Values.spotfireAdminUsername | b64enc | quote }}
  {{- if .Values.spotfireAdminPassword }}
  SPOTFIREADMIN_PASSWORD: {{ .Values.spotfireAdminPassword  | b64enc | quote }}
  {{- else }}
  SPOTFIREADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
kind: Secret
