apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    {{- include "spotfire-common.spotfire-service.labels" . | nindent 4 }}
  name: {{- include "spotfire-fluentbit-configuration.name" . | nindent 4 }}
data:
{{ (.Files.Glob "config/fluent-bit/*.conf").AsConfig | indent 2 }}